# Generated by Django 4.1.4 on 2023-02-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='date_added',
            field=models.DateTimeField(default='1978-07-29'),
            preserve_default=False,
        ),
    ]
