# Generated by Django 4.1.4 on 2023-02-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0002_hotspot_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='year_added',
            field=models.IntegerField(default='1978'),
            preserve_default=False,
        ),
    ]
